SoundRecorder: Add permission for ACCESS_NETWORK_STATE
Fixes the following error:

E AndroidRuntime: java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.android.soundrecorder/com.android.soundrecorder.SoundRecorder}:
java.lang.SecurityException: ConnectivityService: Neither user 10062 nor
current process has android.permission.ACCESS_NETWORK_STATE.

Full exception:

11-24 02:25:06.856 21144 21144 I art     : Failed to open app image
/data/dalvik-cache/arm/system@app@SoundRecorder@SoundRecorder.apk@classes.art
Invalid image header in '/data/dalvik-cache/arm/system@app@SoundRecorder@SoundRecorder.apk@classes.art'
11-24 02:25:06.857 21144 21144 W System  : ClassLoader referenced unknown path:
/system/app/SoundRecorder/lib/arm
11-24 02:25:06.934 21144 21144 D AndroidRuntime: Shutting down VM
11-24 02:25:06.937 21144 21144 E AndroidRuntime: FATAL EXCEPTION: main
11-24 02:25:06.937 21144 21144 E AndroidRuntime: Process: com.android.soundrecorder, PID: 21144
11-24 02:25:06.937 21144 21144 E AndroidRuntime: java.lang.RuntimeException: Unable to
start activity ComponentInfo{com.android.soundrecorder/com.android.soundrecorder.SoundRecorder}:
java.lang.SecurityException: ConnectivityService: Neither user 10062 nor current process has android.permission.ACCESS_NETWORK_STATE.
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6095)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: Caused by: java.lang.SecurityException: ConnectivityService:
Neither user 10062 nor current process has android.permission.ACCESS_NETWORK_STATE.
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1684)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1637)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.net.IConnectivityManager$Stub$Proxy.isNetworkSupported(IConnectivityManager.java:1346)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.net.ConnectivityManager.isNetworkSupported(ConnectivityManager.java:2385)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.telephony.TelephonyManager.getPhoneCount(TelephonyManager.java:230)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at com.android.soundrecorder.SoundRecorder.onCreate(SoundRecorder.java:488)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6679)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2602)
11-24 02:25:06.937 21144 21144 E AndroidRuntime: 	... 9 more
11-24 02:25:06.940   578   763 W ActivityManager:   Force finishing activity com.android.soundrecorder/.SoundRecorder
11-24 02:25:07.010   578 18903 I OpenGLRenderer: Initialized EGL, version 1.4
11-24 02:25:07.010   578 18903 D OpenGLRenderer: Swap behavior 1
11-24 02:25:07.446   578   592 W ActivityManager: Activity pause timeout for ActivityRecord{4502bf9 u0
com.android.soundrecorder/.SoundRecorder t80 f}
11-24 02:25:07.590   578   593 W art     : Long monitor contention with owner ActivityManager (592) at
void com.android.server.am.ActivityStack$ActivityStackHandler.handleMessage(android.os.Message)(ActivityStack.java:378)
waiters=0 in void com.android.server.am.ActivityManagerService.dispatchProcessesChanged() for 142ms
11-24 02:25:07.688   578   588 I art     : Background partial concurrent mark sweep GC freed 29225(1892KB)
AllocSpace objects, 0(0B) LOS objects, 33% free, 14MB/21MB, paused 1.617ms total 199.707ms
11-24 02:25:07.842   578   592 I ActivityManager: Killing 13925:com.android.providers.calendar/u0a5 (adj 906): empty #17
11-24 02:25:07.853   578   590 D ActivityManager: cleanUpApplicationRecord -- 13925

Change-Id: Ic6bdb44c5b426d35db247d5d9d15101a82ed7c31